### ISSUE TITLE
Regarding source domain

### ISSUE THREAD

**Issue by rst1991** [xmed-lab/CPR#1]
@zheangh Which domain you have used as the source dataset Domain 3 or Domain 4? How many images are used for training and validation is source dataset or target dataset. How many images are used in validation if it is Domain 3 or Domain 4?

**Comment by zheangh** [comment]
Hello. In the first adaptation scenario, the source/target domains have been specified in the code. The source dataset is Domain1 and the target dataset is Domain2. In the source domain training, I use the test dataset as validation set. During target domain adaptation, there is no validation set, since target data are unlabeled.
